name: Metadata Checks

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  job:         
    runs-on: [ubuntu-latest]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
        components: rustfmt, clippy
        
    - name: Cargo Doc
      run: cargo doc -p papyrus

    - name: Check Formatting
      run: cargo fmt -- --check

    - name: Check Clippy
      run: cargo clippy --all-features -- -D warnings
